
/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/



/*

Using XOR

*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        char ans = 0;
        if(t.size() <= s.size())
            return ans;
        for(int i = 0; i < s.size(); ++ i){
            ans ^= s[i];
        }
        for(int i = 0; i < t.size(); ++ i){
            ans ^= t[i];
        }
        return ans;
    }
};

/* 
Normal Solution
*/
class Solution {
public:
    char findTheDifference(string s, string t) {
        int i;
        int count_s = 0, count_t = 0;
        for (i = 0; i < s.size(); i++) {
            count_s += int(s[i] - 'a');
        }
        for (i = 0; i < t.size(); i++) {
            count_t += int(t[i] - 'a');
        }
        return 'a' + (count_t - count_s);
    }
};
